### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by YaBoiJaydenO** [ediaz23/crunchyroll-webos-stream#4]
Hi guys. Downloaded this today to try it out and see if I can watch anime here. Created a Crunchyroll account and tried to log onto it but it doesn't work. The image attached shows that the official Crunchyroll account knows that my lg tv is connected(had to blur my location) however the video attached shows that it won't log me in. Already tried to uninstall and reinstall but it didn't work. Any help? Thanks

TV info:
Device: 55UR73006LA
webOS: 8.3.1

https://github.com/user-attachments/assets/9fe38a5e-1d3d-435d-a434-89ec032123bf

![IMG_5472](https://github.com/user-attachments/assets/00647840-8f24-4467-9b40-dc5e48d516b1)

**Comment by ediaz23** [comment]
I've created a brand new account, tested it and it worked.
Do you verify your email in crunchyroll?
Can you remove device in your crunchyroll account and log in again?
Can you test mobile app on your phone (this app workes with same api)?

I need all information that you can give me because i just can not reproduce this error, so if i can not reproduce it i cannot fix it.

Tell me everything you can.
Do you use this account normally?
How long have you had this account?
Did you start free trial and it ended?
Can you already see multiprofiles in your account?

Again, I need to be able to reproduce this error.

**Comment by YaBoiJaydenO** [comment]
Hi sorry for the late reply,
I verified my email address
Removed my device from the crunchyroll account and logged back in and it still wouldn't work
Downloaded the crunchyroll app on my phone, logged in and it works
Don't use the account normally since this is the first time I'm using it
Had the account since 12th July 2024 (like mentioned this is my first time using crunchyroll)
No I didn't start a free trial
I can see the multi profile on my phone

**Comment by ediaz23** [comment]
Hi, thanks, I'm working on a view to make some test. I'll try to release a new version this week.

**Comment by ediaz23** [comment]
I already realsed a new version. I think i could find the bug, so it should be working now, but if it's not working I added a new dev view to do some test.
[realse](https://github.com/ediaz23/crunchyroll-webos-stream/releases/tag/v1.1.3)

Please, let me know if it's working now.

**Comment by YaBoiJaydenO** [comment]
Hey, It works now thank you so much!
